### ISSUE TITLE
openCyto gating algorithms questions

### ISSUE THREAD

**Issue by anaraserikbek** [RGLab/openCyto#110]
1. What would you recommend for using for 2D gating? I saw you posting about flowDensity vs flowClust+mindensity method? How does it influence the results when we do 2 1D gates versus if we gate the same population using 2D gate? 
2. When plotting after gating using a .csv hand-written gating-template, my graph names have the parent population name. How to change this so that my graphs display the population name it is gating for? 
3. How derive & display at the same time the cell count for each gated population on the plots? (without having to write count function for each) 
4. In pre-processing, how to compensated the .fcs files as one flowSet, when each .fcs file was obtained at different weeks & thus has different compensation matrices (but of the .fcs files contain the matrices inside), thus cannot be compensated with 1 compMatrix? 
5. What's the difference in installing the different packages from Bioconductor vs. installing through github? 
6. How risky is it to specify the gate_range in the mindensity method (and in others, where possible), since depending on the acquicisition parameters the data might differ.
7. How do we find the threshold for cytokine gating_method? what the **tol (tolerance) & adjust** parameters specify exactly? (in the function tol is the tolerance used to construct the cytokine gate, but what does that mean?)
8. is there difference between tailgate and cytokine gating methods? 
9. Not all flow machines' .fcs files have the same format. I'm working with .fcs files acquired with BD, however there're other machines that don't have the same format. Will openCyto support these formats? 
10. When creating a gating-template manually as .csv file, one of my markers/channels' name is **TCRVa7-2** & when I specify a population name as (for example) TCRVa7-2+/- or just TCRVa7-2+, the computer sees the - between 7&2 as negative, how can I overcome this issue? would using position TRUE,FALSE give me this result? Because if I want to gate on 2 markers and save all 4 gates & specify in the pop column A+/-B+/-, it doesn't allow this with the marker name **TCRVa7-2?** 
11. Would there be any webinars (as the one on youtube with Greg Finak & TJ Chen & Ryan Duggan) on openCyto or even workshops,etc. where we'd be able to learn first-hand and ask all questions? 

Thank you in advance ! 
as I was saying earlier if it's too much to type, we can always call if it'd be faster/more convenient for the package developers. 
also, I can create a separate issue#/issue for each question, if you'd consider it more appropriate.

**Comment by mikejiang** [comment]
https://www.bioconductor.org/help/course-materials/2014/BioC2014/OpenCytoPracticalComponent.htmlA1: I will put up a vignette for that as promised

A2: with `ggcyto` package, you are able to switch from `parent` to `gate` name by `strip.text` argument,
see details in `?autoplot.GatingHierarchy`

A3: there is `type` argument for `geom_stats` layer, see `?geom_stats`

A4: You should loop through `flowSet` and compensate each individual `flowFrame`. e.g.
```r
fs_comp <- fsApply(fs, function(fr){
            comp <- spillover(fr)[["$SPILLOVER"]] #could be SPILL
            compensate(fr, comp)
            })
```
A5: `bioc` is stable version, `git` is considered to be bleeding edge (although `bioc devel` branch is pretty much synced with `git trunk` once a week

A6: `gate_range` should be as vague/large as possible so that it is applicable across different data sets. The main purpose for this parameter is to prevent the algorithm from being interfered by some extreme outlier signals

A7-8: `Cytokine` gate is deprecated by `tailgate`, See `?tailgate` for the details of its parameters

A9:  As long as these FCS files can be loaded with `flowCore` through `read.FCS`, they should be ready to use in `openCyto`

A10: `pop` column doesn't look at the actual `population name`, it is the `alias` column that defines the name, so you can simply put `A+/-B+/-` in `pop` column

A11: Here are two workshops done by @gfinak in the past
https://github.com/gfinak/BioC2015OpenCyto
https://www.bioconductor.org/help/course-materials/2014/BioC2014/OpenCytoPracticalComponent.html

**Comment by anaraserikbek** [comment]
Thank you a lot Mike! Especially for Q10, it's working now
