### ISSUE TITLE
application of mclust for clustering .FCS data

### ISSUE THREAD

**Issue by anaraserikbek** [RGLab/openCyto#119]
hi everyone, 
I've tried to use **mclust** on flow cytometry data (**.FCS file**). mclust cannot directly be applied on .FCS data and I tried to convert it to a matrix using as.matrix. However, in both cases, I receive an Error:
`as.vector(data): No method for coercing this S4 class to a vector.`

I've found online that you're supposed to add `importFrom(BiocGenerics,as.vector)` in the **NAMESPACE** file of the mclust package & also specify in the **DESCRIPTION** that **Depends:BiocGenerics.** 
However, I've tried several options, adding both as.vector & as.matrix functions, and I still receive this error. I believe I'm missing some basic knowledge. I'd really appreciate some clarification or some suggested reading on this. 
thanks in advance,

**Comment by gfinak** [comment]
Hi, @anaraserikbek. Sorry your issue was missed. Mclust is not our package. We don't support it. You need to convert the data you read in from the FCS file into a flowframe and then grab the matrix. You can do that with the exprs() method. But you'll lose a lot of important metadata in the flow frame in the process.
