### ISSUE TITLE
Unique alias name

### ISSUE THREAD

**Issue by kdh4win4** [RGLab/openCyto#138]
```R
gt_yohann_1 <- gatingTemplate("gt_080_y_m_boundary.csv") # for single set, key causion,

expanding pop: G660-/+ R730+/-

expanding pop: R780+/-G780+/-

expanding pop: V450+/-B515+/-

expanding pop: G575+/-V450+/-

Error in **.unique_check_alias(**new_dt, thisAlias, row[["parent"]]) : 
  **V450+ is not unique
[gt_080_y_m_boundary.xlsx](https://github.com/RGLab/openCyto/files/914386/gt_080_y_m_boundary.xlsx)

** within /boundary/singlet/viable/nonNeutro/G660-R730-/G780+
In addition: Warning messages:
1: In `[.data.table`(dt, , `:=`(col, as.character(newCol)), with = FALSE) :
  with=FALSE together with := was deprecated in v1.9.4 released Oct 2014. Please wrap the LHS of := with parentheses; e.g., DT[,(myVar):=sum(b),by=a] to assign to column name(s) held in variable myVar. See ?':=' for other examples. As warned in 2014, this is now a warning.
```
[gt_080_y_m_boundary.xlsx](https://github.com/RGLab/openCyto/files/914393/gt_080_y_m_boundary.xlsx)

**Comment by kdh4win4** [comment]
Each V450, B515, G575 channel names appear twice in alias column. That makes the problem.
How can I solve or detour this issue?
Thank you.

**Comment by mikejiang** [comment]
![image](https://cloud.githubusercontent.com/assets/1385649/24926495/9c94dff0-1eb0-11e7-952f-22ca6d30acb6.png)
These 3 quadgates share the same parent `G780+` and the dimensions overlap among those 3 channels, which causes the `1d` gates for each of these channels to be created twice. To avoid that, you should do `1d` gating explicitly on these channels and construct quadgate based on `1d` gate using `refGate`, e.g.
![image](https://cloud.githubusercontent.com/assets/1385649/24926937/1db0c698-1eb2-11e7-8d42-9a86e81d8f82.png)

see the manual for more details https://www.bioconductor.org/packages/release/bioc/vignettes/openCyto/inst/doc/HowToWriteCSVTemplate.html#13_pop_=_“+-+-”

**Comment by coh-racng** [comment]
I have also encountered the same problem. I have tried using refgate in the following template:

alias | pop | parent | dims | gating_method | gating_args
-- | -- | -- | -- | -- | --
nonSaturation | + | root | FSC-A,SSC-A | boundary | min=c(0, 0),max=c(2.4e5, 2.4e5)
nonDebris | + | nonSaturation | FSC-A,SSC-A | flowClust | K=1, transitional = T, translation = 0, transitional_angle = pi*.25
DAPI- | - | nonDebris | DAPI-A | tailgate | tol=0.05
CD3_gate | + | DAPI- | CD3-VioGreen-A | mindensity.filtered | peaks=TRUE, positive=FALSE, pivot=TRUE, gate_range=c(2,3)
CD8_gate | + | DAPI- | CD8-APC-Cy7-A | tailgate.filtered | tol=0.05
PD1_gate | + | DAPI- | PD1-FITC-A | tailgate.filtered | tol=0.05
CD69_gate | + | DAPI- | CD69-PE-A | tailgate.filtered | tol=0.05
CD95_gate | + | DAPI- | CD95-PerCP-Cy5.5-A | tailgate.filtered | tol=0.05
CD19_gate | + | DAPI- | CD19-PE-Cy7-A | tailgate.filtered | tol=0.05
CD25_gate | + | DAPI- | CD25-APC-A | tailgate.filtered | tol=0.05
CD3+CD8+ | + | CD3_gate | CD8-APC-Cy7-A | refgate | CD8_gate
\* | +/-+/- | DAPI- | CD8-APC-Cy7-A,PD1-FITC-A | refgate | CD8_gate:PD1_gate
\* | +/-+/- | DAPI- | CD8-APC-Cy7-A,CD69-PE-A | refgate | CD8_gate:CD69_gate

I get an error 
`Error in .unique_check_alias(new_dt, thisAlias, row[["parent"]]) : 
  CD8-APC-Cy7-A+ is not unique within /nonSaturation/nonDebris/DAPI-`
The error is gone if I remove the last entry; however, I do need both quadgates and many more combinations.

On the other hand, if I put 'A+/-B+/-' instead of '+/-+/-', I get the error
`Error in .preprocess_row(this_row, strict = strict) : 
  'pop': A+/-B+/- should only contain the + and - symbols and must conform to the valid +/- or +/-+/- patterns! Please remove any other letters and correct the pop pattern!` 

Please let me know of any suggestions/solutions. Thanks!
