### ISSUE TITLE
read.ncdfFlowSet("fs from several different directories")

### ISSUE THREAD

**Issue by kdh4win4** [RGLab/openCyto#142]
Dear Mike and Finak, 

Using "union()" function, I assembled several fcs_files like below code. 
```R
setwd("/Volumes/Flow_Core/directory_one/")
fcs_file_1 <- Sys.glob('NKcell*.fcs')
setwd("/Volumes/Flow_Core/directory_two/")
fcs_file_2 <- Sys.glob('NKcell*.fcs')
setwd("/Volumes/Flow_Core/directory_three/")
fcs_file_3 <- Sys.glob('NKcell*.fcs')
fcs_file_123 <- union(union(fcs_file_1,fcs_file_2),fcs_file_3)
fs <- read.ncdfFlowSet(fcs_file_123)  # There is an error. They only can read the last one. directory_three. 
```
I understand the error. 
I would like to read all fcs files which are in several different directories. 
Can I know how to solve this issue ?
Thank you.

**Comment by gfinak** [comment]
Check that your file paths are correct, try reading each one individually, isolate the problem. This is not an OpenCyto issue, there is no inherent reason you shouldn't be able to read FCS files from different directories.

**Comment by kdh4win4** [comment]
Dear Dr Greg, 
Then, is there any way to combine or merge several "ncdfFlowSet" files into one?

**Comment by gfinak** [comment]
I believe merge2 does this, either for gating sets or ncdfFlowSets.

**Comment by mikejiang** [comment]
What is the error message?  what is the content of `fcs_file_123`? I think it is generally a bad practice to `setwd` in your script, you should avoid it and do this instead
```r
fcs_file_1 <- Sys.glob('/Volumes/Flow_Core/directory_one/NKcell*.fcs')
```
As Greg said, this is the generic basic `R` question which really belongs to `stackoverflow`  or [R-help](https://stat.ethz.ch/mailman/listinfo/r-help).

Regarding to merging, see [rbind2](https://www.rdocumentation.org/packages/ncdfFlow/versions/2.18.0/topics/rbind2,ncdfFlowList,ANY-method)
But, it is unnecessary because you should be able to read them all at once once you concatenate file paths properly

**Comment by mikejiang** [comment]
By the way, Do these directories contains the fcs files that have the same names?

**Comment by kdh4win4** [comment]
I did not finish installing npm merge2 yet. 
setwd() has no issue. 
My apology on confusing.

**Comment by gfinak** [comment]
I misspoke. Mike has it right, the function is rbind2

**Comment by kdh4win4** [comment]
I will try rbind2 soon. I appreciate it.

**Comment by kdh4win4** [comment]
I solved this issue. Thank you very much.
