### ISSUE TITLE
Unable to find an inherited method for function ‘filterObject’ for signature ‘"boundaryFilter"’

### ISSUE THREAD

**Issue by epgui** [RGLab/openCyto#163]
I've been trying to follow along the [flowStats vignette](https://www.bioconductor.org/packages/devel/bioc/vignettes/flowStats/inst/doc/GettingStartedWithFlowStats.pdf), which appears to be outdated because the _**workFlow** Object_ it refers to has since been deprecated. It seems like it was simply replaced by the _**gatingSet** Object_, so I attempted to follow along with the help of this [openCyto vignette](http://opencyto.org/openCytoVignette.html). Abstracting away the parts of my code that works, I get:

```
> # data and t.Data are of type flowSet. transformData works properly.
> t.data <- transformData(data)

> # Add transformed data to a GatingSet
>   gs <- GatingSet(t.data)
........done!

> # Remove boundary events
> boundFilt <- boundaryFilter(filterId = "boundFilt", x = c("FS Lin", "SS Lin"))
> add(gs, boundFilt)
replicating filter 'boundFilt' across samples!
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘filterObject’ for signature ‘"boundaryFilter"’

```

After looking at the source code for openCyto, am I correct in interpreting this:

1. as an openCyto bug, and;
2. as a result of the fact that the defined signature in openCyto is "boundary" and not "boundaryFilter", perhaps due to some changes in flowCore?

Please advise, and thank you!

**Comment by mikejiang** [comment]
It is not a bug. `GateSet` is the replacement for `workflow`, but does not meant to be the exact equivalent data container as its predecessor. Lots of filter or gate types defined in `flowCore` did not turned out to be useful for the common analysis thus were not implemented in `GateSet`.
Here is the list of gates currently supported by `GateSet`
* 3 major geometrical gates(up to 2d) , 
  * `rectangleGate`
  *  `polygonGate`
  * `ellipsoidGate` 
* `booleanGate` boolean combination of existing gates
*  `logical` gate representing the gating results from the gate that doesn't have geometrical shape (e.g. clustering gating).
   * `filterResult` 
   * or the generic `factor` or `logical` vector 

That said, other gates (e.g. `boundaryFilter`) can be considered to be added to this list if necessary.

For the time being, you can use `openCyto:::.bondary` , which is essentially a `rectangle` gate with hand-set thresholds (thus not relevant to `boundaryFilter`).
e.g.
```r
library(openCyto)
library(ggcyto)

data("GvHD")
fs <- GvHD[1]
gs <- GatingSet(fs)

add_pop(gs,alias = "boundFilt"
        , parent = "root"
        , dims = "FSC-H,SSC-H"
        , gating_method = "boundary"
        , gating_args = "min=c(10,20),max =c(700,800)")
autoplot(gs, "boundFilt")
```
![image](https://user-images.githubusercontent.com/1385649/33625199-ab0fc868-d9ab-11e7-87b8-16a62efd2239.png)

If you do need a more data-driven approach, you can still use `boundaryFilter`, but must apply it to the data and  add its `filterResult` to `gs`
```r
bf <- boundaryFilter(x = c("FSC-H", "SSC-H"))
fres <- filter(fs, bf)
add(gs, fres, parent = "root", name = "bf_bool")
```
However, since it is now saved as `logical` gate without any dimension information associated , you can't visualize it on its way except by overlaying it on top of the other gates or data.
```r
autoplot(gs, "boundFilt") + geom_overlay("bf_bool", size = 0.3)
```
![image](https://user-images.githubusercontent.com/1385649/33625397-471aee40-d9ac-11e7-8f90-6fe2f1545281.png)
```r
```

**Comment by epgui** [comment]
Wow thanks so much for clarifying this @mikejiang ... Everything makes sense now, but the documentation of pretty much every flow tool on bioconductor is incredibly confusing because they don't seem to be kept up to date with changes like these.

I don't mean to be rude, I appreciate all the good work that went into these and if I was a little more comfortable with the tools I'd love to help out and contribute myself to keeping the docs up to date... but in the meantime perhaps someone who knows more than me should be assigned to keep the docs and vignettes up to date over at bioconductor? I know that would certainly help a lot of people get on board with using R for flow analysis, and would probably be good for the user base :)

Thanks for the pointers!!

**Comment by gfinak** [comment]
@epgui 
We are about two people, one full time, working on maintaining the Bioconductor flow infrastructure. The tools are entirely open source so if you are interested, feel free to update docs when you see errors or omissions, or if you have an idea for a vignette to demonstrate a particular process.  The best way is probably via pull requests here on github. We'd welcome it and happy to give credit. 
Best
Greg

**Comment by epgui** [comment]
Keep it up! I love these tools, and I wish we'd see wider adoption. I'll try to help whenever I can!
