### ISSUE TITLE
convert an existing gating Hierarchy to the csv gating template

### ISSUE THREAD

**Issue by mikejiang** [RGLab/openCyto#67]
To ease the process of writing csv template to replicate the manual gating schemes, we can generate a csv gating template with the `alias`,`pop`,`parent` and `dims` parsed from `xml`, and leaving the gating methods columns blank for user to complete.

**Comment by mikejiang** [comment]
As discussed at yesterday's meeting, when translating a `manual` `rectangleGate` into appropriate `1d gating method`,   besides comparing the `geometric` boundary of the gate to the `data range`, we will also look at the `1d kernel density` to determine whether `mindensity` or `tailgate` should be applied.

For now, I am only looking at one sample, once we have a working prototype, it can be extended to use multiple samples as @gfinak suggested.

**Comment by anaraserikbek** [comment]
Hello, thanks for the useful information. Is it possible to extract not only the 4 column information, but also the gating_method, groupBy, CollapseDataForGating § preprocessing columns from the existing gating template? Would you not recommend getting other such parameters and instead fill them in manually in the excel sheet? If so, is there any full/comprehensive list of gating methods and preprocessing methods. There are examples, but even the openCyto package vignette § description doesn't contain detailed explanation on different gating methods to decide which one to use in each step. 
Thank you

**Comment by mikejiang** [comment]
We can't get those columns from `GatingSet` because they are simply not stored in `GatingSet`.

Any gating methods can be used as the `plugin` of the `openCyto` as long as it conforms to the conventions.  But It is actually a good idea to have a separate vignette to list all gating methods naively supported by `openCyto`.

**Comment by anaraserikbek** [comment]
Thank you Mike. Are you suggesting for me to create a vignette to demonstrate the usages of different gating methods? 
I have created my own gating template, but I've been received an **Error in UseMethod ("alias"): no applicable method for 'alias' applied to an object of class "gtPopulation". ** 
i have created a gating template similar to the openCyto's "how to create an automated gating". What could this error be caused by ?

**Comment by mikejiang** [comment]
No. We will be writing such vignette. And the error of `alias` is also known issue, which has to do with the method masking due to the same `S4` generic was defined in other packages. I will try to reproduce and fix it.

**Comment by anaraserikbek** [comment]
Hi Mike, thanks once more. 
I'm relatively new to R & FCM data analysis & I'm writing a pipeline for a data set of clinical immunology trial of our lab. I have the following questions (I'm not sure if I need to create a threat for each of these questions separately?) If the questions are too many, or, if it'd be easier to answer them by phone, I am located in Paris (Institut Curie, U932 Flow Cytometry), let me know your availability & I'll call. 

## Q1: As I understood, the method masking error that I've got before was due to the fact that 'alias' method was present no only in this, but in other packages; and, so with the code you provided, you converted it into a private function of this package? [I've read about S4 classes & masking, but still seem to be confused]. Along with this, since the research personal in our lab will be using this pipeline in the future, would they always need to solve this masking issue in R while analyzing a new new .FCS data set? Is there a way to make it incorporated into openCyto package (when you already download the package. so that they don't have to write code...)? 

## Q2: What is the purpose of the 4th file "man/alias-gtPopulation-method.Rd" 
 -% Please edit documentation in R/gtPopulation-methods.R ... 

## Q3: for the automated-gating scheme, the gating_methods vignette will be very useful. When do you think we should be expecting the vignette for this?

## Q4: For using a manual-gating-template from FlowJo, it seems that for every .fcs file of the FlowSet, we need to read/open its corresponding Workspace from R as a gating template. Or is there a way to use one Workspace gating template with its parameters to apply for all the FlowSet .fcs files? (does the FlowJo workspace gating-template already contain the information about the .fcs file that it's supposed to be applied to? Since, i've tried to apply a gating template of, for example,"1.fcs" to "2.fcs" & it does not work.)

## Q5: which gating method (automated vs. incorporated from flowJo) could be more beneficial in analyzing clinical data (small subset 70-80 patients, 4 times points, 19 markers)? (In automated gating template, how risky is it to use the gating_methods with set parameters in analyzing a big flowSet)

**Comment by mikejiang** [comment]
1: `alias` problem is already fixed.
2: This file no longer exists after the fix
3: Probably next week
4: Not implemented yet If you are talking about [this](https://github.com/RGLab/flowWorkspace/issues/197)
5. Try to create a separate issue and elaborate more

**Comment by anaraserikbek** [comment]
Okay, great. We appreciate your help. 
How can I sign up to get a notification when the gating_method vignettte will be available? or should i just keep checking on openCyto website? 
(regarding Q4): yes, I was talking about that process. But does that mean that for each .FCS file of each patient to work with flowJo-template, we need to manually analyze on flowJo and then use that template in R to reproduce the gating on R? Does that mean that the gating_method/information is already incorporated in these flowJo workspace files? Then, would it be possible to extract not only the alias,pop,parent,dims information, but also the gating method and processing parameters?

**Comment by mikejiang** [comment]
If you `watch` this issue https://github.com/RGLab/openCyto/issues/107 and then you will be notified once it is closed.
I still don't understand you question regarding to Q4 and it sounds irrelevant to this thread. Can you open a new issue and give a concrete example to illustrate what you aim for?
